// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/sanpham": {
    params: {};
  };
  "/kho": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/shop": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/security": {
    params: {};
  };
  "/MalikethPolicy": {
    params: {};
  };
  "/ReturnRefundPolicy": {
    params: {};
  };
  "/TermsOfService": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/sanpham" | "/kho" | "/product/:id" | "/shop" | "/cart" | "/checkout" | "/security" | "/MalikethPolicy" | "/ReturnRefundPolicy" | "/TermsOfService";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./src/components/page/LoginPage.jsx": {
    id: "src/components/page/LoginPage";
    page: "/login";
  };
  "./src/components/page/Dashborad.jsx": {
    id: "src/components/page/Dashborad";
    page: "/dashboard";
  };
  "./src/components/page/admin/Sanpham.jsx": {
    id: "src/components/page/admin/Sanpham";
    page: "/sanpham";
  };
  "./src/components/page/admin/Kho.jsx": {
    id: "src/components/page/admin/Kho";
    page: "/kho";
  };
  "./src/components/page/ProductDetail.jsx": {
    id: "src/components/page/ProductDetail";
    page: "/product/:id";
  };
  "./src/components/layout/CrateShop.jsx": {
    id: "src/components/layout/CrateShop";
    page: "/shop";
  };
  "./src/components/page/Cart.jsx": {
    id: "src/components/page/Cart";
    page: "/cart";
  };
  "./src/components/page/checkout.jsx": {
    id: "src/components/page/checkout";
    page: "/checkout";
  };
  "./src/components/ui/operating_policy/security.jsx": {
    id: "src/components/ui/operating_policy/security";
    page: "/security";
  };
  "./src/components/ui/operating_policy/MalikethPolicy.jsx": {
    id: "src/components/ui/operating_policy/MalikethPolicy";
    page: "/MalikethPolicy";
  };
  "./src/components/ui/operating_policy/ReturnRefundPolicy.jsx": {
    id: "src/components/ui/operating_policy/ReturnRefundPolicy";
    page: "/ReturnRefundPolicy";
  };
  "./src/components/ui/operating_policy/TermsOfService.jsx": {
    id: "src/components/ui/operating_policy/TermsOfService";
    page: "/TermsOfService";
  };
};