// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "../app/src/components/page/LoginPage.jsx": {
    id: "../app/src/components/page/LoginPage";
    page: "/login";
  };
};